In [29]:
from sklearn.datasets import load_digits

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
digits = load_digits()

In [32]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [35]:
# Let's import some models to test 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [36]:
Lmodel = LogisticRegression()
Lmodel.fit(X_train,Y_train)
Lmodel.score(X_test,Y_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [37]:
svcmodel = SVC()
svcmodel.fit(X_train,Y_train)
svcmodel.score(X_test,Y_test)

0.9851851851851852

In [38]:
Rmodel = RandomForestClassifier()
Rmodel.fit(X_train,Y_train)
Rmodel.score(X_test,Y_test)

0.9666666666666667

# KFold cross validation

In [39]:
from sklearn.model_selection import KFold

In [40]:
Kmodel = KFold(n_splits=4)

In [41]:
# example of implimenting KFold 
for train_index, test_index in Kmodel.split([1,2,3,4,5,6,7,8,9,10,11,12]):
    print(train_index,test_index)
# the first horizontal array gives the train_index and the second is the test_index    

[ 3  4  5  6  7  8  9 10 11] [0 1 2]
[ 0  1  2  6  7  8  9 10 11] [3 4 5]
[ 0  1  2  3  4  5  9 10 11] [6 7 8]
[0 1 2 3 4 5 6 7 8] [ 9 10 11]


## Use KFold for our digits dataset

In [42]:
# let's define a function which can give the score easily by taking the following entries specified.
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [43]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
# we have given the empty list for the score 
scores_logistic = []
scores_svm = []
scores_rf = []

In [44]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
# data  for traing and testing
# target for training and testing   
# scores_p.append(get_score(model, X_train, X_test, y_train, y_test))  
# filling up the list

In [45]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [46]:
# converting to Numpy array as now we can perform some algebric operations.
scores_logistic = np.array(scores_logistic) 

In [47]:
scores_logistic.mean()

0.9193099610461881

In [48]:
scores_rf

[0.9248747913188647, 0.9449081803005008, 0.9332220367278798]

In [49]:
scores_rf = np.array(scores_rf)

In [50]:
scores_rf.mean()

0.9343350027824151

In [51]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [52]:
scores_svm = np.array(scores_svm)

In [53]:
scores_svm.mean()

0.4346132442960489